env:
  global:
  - CC_TEST_REPORTER_ID=70ede70cf252120a6c9699e53a5f6767d64910e44c0a64a6478e70379a6a28b7
sudo: false
language: ruby
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
cache: bundler
rvm:
- 2.3.8
- 2.4.6
- 2.5.5
- 2.6.3
before_install: gem install bundler
script:
- bundle exec rspec
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
